# Generated by Django 4.2 on 2023-10-31 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_registro_mongo_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro',
            name='machine_id',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='registro',
            name='sensor_id',
            field=models.CharField(max_length=128),
        ),
    ]
