# Generated by Django 4.2 on 2023-11-01 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_registro_machine_id_alter_registro_sensor_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro',
            name='value',
            field=models.FloatField(null=True),
        ),
    ]
