# Generated by Django 4.2 on 2023-11-01 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_registro_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro',
            name='company_id',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='registro',
            name='machine_id',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='registro',
            name='sensor_id',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='registro',
            name='timestamp',
            field=models.DateTimeField(null=True),
        ),
    ]
